FROM docker.io/golang:1.22 as builder
ADD . /go/ping_exporter/
WORKDIR /go/ping_exporter
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -a -installsuffix cgo -o /go/bin/ping_exporter


FROM docker.io/alpine:3.20.0 as certificates
RUN apk --no-cache add ca-certificates

FROM scratch
WORKDIR /app
COPY --from=certificates /etc/ssl /etc/ssl
COPY --from=builder /go/bin/ping_exporter /app/ping_exporter

ENTRYPOINT ["/app/ping_exporter"]
