name: build
on: 
  push:
    branches:
      - master
      - feature/*
jobs:
  build:
    name: build golang
    runs-on: ubuntu-20.04
    steps:
      - name: clone
        uses: actions/checkout@v2
      - name: install depends
        run: |
          go mod download
          mkdir artifacts
      - name: build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o artifacts/ping_exporter-amd64 .
          CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o artifacts/ping_exporter-386 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o artifacts/ping_exporter-arm8 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o artifacts/ping_exporter-arm7 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -o artifacts/ping_exporter-arm6 .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=5 go build -o artifacts/ping_exporter-arm5 .
      - uses: kentik/pkg@v1
        with:
          name: ping_exporter
          version: 0.0.1
          arch: x86_64
          format: deb
          package: package.yaml
      - run: |
          git status
          ls -la
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ping_exporter
          path: artifacts/*