name: release
concurrency:
  group: release
  cancel-in-progress: true
on: 
  push:
    tags:
      - '*.*.*'
jobs:
  build_and_release:
    name: build_and_release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "1.22"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        id: goreleaser
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
  container_image:
    name: container_image
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.set-image-name.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: image name
        id: set-image-name
        run: |
          name="$(echo ${{ github.repository }} | tr 'A-Z' 'a-z')"
          echo "image=ghcr.io/$name:${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          context: .
          file: ./Dockerfile_custom
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.set-image-name.outputs.image }}
  
  edit_release:
    name: release
    runs-on: ubuntu-22.04
    needs: [build_and_release, container_image]
    steps:

    - name: ${{ github.ref_name }}
      uses: softprops/action-gh-release@v2
      with:
        append_body: true
        body: |
          *container image*:
          ```
          ${{ needs.container_image.outputs.image }}
          ```